# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a71d1ab0c603f4a82297707dffea8c1d5146242985b5dce5a6e9c81489e1b663ce09cfc682a5f1524987490f94d8c60a2fa61ebc1481c9ff9c2e37282e27de9

test:
  secret_key_base: f32d41cbddcc1dc5b2f8800898d1831c9d8843f0880795c98e7f654b62642db206bb24a888c46f7c34685c2ab9743e17f23c11ca62e9a7c50dca48cf090db478

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
